development:
  sessions:
    default:
      database: precision
      hosts:
        - localhost:27017
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
test:
  sessions:
    default:
      database: precision-test
      hosts:
       - localhost:27017
  options:
    allow_dynamic_fields: false
    raise_not_found_error: false
